###########################################
#Welcome to zUMIs
#below, please fill the mandatory inputs
#We expect full paths for all files.
###########################################

#define a project name
project: tiny

#Sequencing File Inputs:
#For each input file, make one list object & define path and barcode ranges
#base definition vocabulary: BC(n) UMI(n) cDNA(n).
#Barcode range definition needs to account for all ranges. You can give several comma-separated ranges for BC & UMI sequences, eg. BC(1-6,20-26)
sequence_files:
  file1:
    name: /data/share/common/scripts/UMI_pipeline/zUMIs/ExampleData/barcoderead_HEK.1mio.fq.gz
    base_definition:
      - BC(1-6)
      - UMI(7-16)
  file2:
    name: /data/share/common/scripts/UMI_pipeline/zUMIs/ExampleData/cDNAread_HEK.1mio.fq.gz
    base_definition:
      - cDNA(1-50)

#STAR reference genome setup
reference:
  STAR_index: /data/ngs/genomes/Human/hg38/STAR5idx_noGTF
  GTF_file: /data/ngs/genomes/Human/hg38/Homo_sapiens.GRCh38.84_chrsNamesUCSC.gtf
  additional_files:
    - /data/ngs/genomes/artificial_sequences/spikes/ERCC92.fa #possible additional reference sequences, eg ERCC.fa
  additional_STAR_params: null #add custom mapping parameters to STAR

#output directory
out_dir: /data/share/htp/zUMIs2/onemillion

###########################################
#below, you may optionally change default parameters
###########################################

#number of processors to use
num_threads: 12
mem_limit: 50 #Memory limit in Gigabytes, null meaning unlimited RAM usage.

#barcode & UMI filtering options
#number of bases under the base quality cutoff that should be filtered out.
#Phred score base-cutoff for quality control.
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20

#Options for Barcode handling
#You can give either number of top barcodes to use or give an annotation of cell barcodes.
#If you leave both barcode_num and barcode_file empty, zUMIs will perform automatic cell barcode selection for you!
barcodes:
  barcode_num: null
  barcode_file: null
  BarcodeBinning: 0 #Hamming distance binning of close cell barcode sequences. ATTENTION! This option is currently not implemented!
  nReadsperCell: 100 #Keep only the cell barcodes with atleast n number of reads.

#Options related to counting of reads towards expression profiles
counting_opts:
  introns: yes #can be set to no for exon-only counting.
  downsampling: 0 #Number of reads to downsample to. This value can be a fixed number of reads (e.g. 10000) or a desired range (e.g. 10000-20000) Barcodes with less than <d> will not be reported. 0 means adaptive downsampling. Default: 0.
  strand: 0 #Is the library stranded? 0 = unstranded, 1 = positively stranded, 2 = negatively stranded
  Ham_Dist: 0 #Hamming distance collapsing of UMI sequences.
  velocyto: no #Would you like velocyto-compatible counting of intron-exon spanning reads
  primaryHit: yes #Do you want to count the primary Hits of multimapping reads towards gene expression levels?

#produce stats files and plots?
make_stats: yes

#use SLURM workload manger?
use_SLURM: no

#Start zUMIs from stage. Possible TEXT(Filtering, Mapping, Counting, Summarising). Default: Filtering.
which_Stage: Filtering

#below, the fqfilter will add a read_layout flag defining SE or PE
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
zUMIs_directory: /data/share/htp/zUMIs2/zUMIs
read_layout: SE
